# This is a basic test workflow to trigger an echo action on a push event

name: Echo_Event

# Controls when the workflow will run
on:
  # Triggers the workflow on push event but only for the "development" branch
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: |
      echo New files have been added
